version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile 
      
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"  
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=laravel
    depends_on:
      - mysql  

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:  